name: ibd-antitnf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - statsmodels
  - scanpy
  - anndata
  - jupyterlab
  - ipykernel
  - lxml
  - tqdm
  - pip:
      - gseapy
      - pydeseq2

