name: scr_smoke
channels:
  - conda-forge
dependencies:
  - anndata
  - leidenalg
  - matplotlib
  - numpy
  - pandas
  - python-igraph
  - python=3.11
  - pyyaml
  - scanpy
  - libblas[build=*openblas]

